name: Build

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            target: windows-all
            arch: ia32,x64
            dist: 'dist'
            installer_pattern: 'dist/Better-CrewLink Setup*.exe'
            unpacked_path: ''
          - os: windows-latest
            target: windows-x64
            arch: x64
            dist: 'dist'
            installer_pattern: 'dist/Better-CrewLink Setup*.exe'
            unpacked_path: ''
          - os: windows-latest
            target: windows-x64-unpacked
            arch: x64
            dist: 'dist'
            installer_pattern: ''
            unpacked_path: 'dist/win-unpacked'
          
          # Linux builds
          - os: ubuntu-latest
            target: linux-all
            arch: ia32,x64
            dist: 'dist:linux'
            installer_pattern: 'dist/Better-CrewLink-*.AppImage'
            unpacked_path: ''
          - os: ubuntu-latest
            target: linux-x64
            arch: x64
            dist: 'dist:linux'
            installer_pattern: 'dist/Better-CrewLink-*.AppImage'
            unpacked_path: ''

    steps:
      - name: Install Windows Build Tools
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Linux dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb1-dev libx11-dev

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 16.14.2
        
      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-${{ matrix.target }}-${{ hashFiles('yarn.lock')}}
    
      - name: Install Dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install --cache-folder .yarn --network-timeout 100000
        
      - name: Build App
        run: yarn run ${{ matrix.dist }} --publish never --${{ matrix.arch }}
     
      - name: Upload Installer
        if: ${{ matrix.installer_pattern != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: BetterCrewLink ${{ matrix.target }}
          path: ${{ matrix.installer_pattern }}
          if-no-files-found: error
          
      - name: Upload Unpacked
        if: ${{ matrix.unpacked_path != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: BetterCrewLink ${{ matrix.target }}
          path: ${{ matrix.unpacked_path }}
          if-no-files-found: error